### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by fredriksvantes** [rolfwessels/Command.Bot#1]
Hey,

Your bot is great, but it seems quite prone to crashing from time to time, and then you must restart it (at least if it is started with Command.Bot.exe run:

```
2017-07-07 04:14:35|Fatal|WebSocket.processException:0|WebSocketSharp.WebSocketException: The header part of a frame cannot be read from the data source.
                             at WebSocketSharp.WebSocketFrame.<>c__DisplayClass7.<ReadAsync>b__6(Byte[] header)
                             at WebSocketSharp.Ext.<>c__DisplayClass6.<ReadBytesAsync>b__5(IAsyncResult ar)
2017-07-07 08:18:32|Fatal|WebSocket.error:0|System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
                             at System.Threading.Tasks.TaskCompletionSource`1.SetException(Exception exception)
                             at WebSocketSharp.Ext.Emit[TEventArgs](EventHandler`1 eventHandler, Object sender, TEventArgs e)
                             at WebSocketSharp.WebSocket.error(String message, Exception exception)
```

**Comment by rolfwessels** [comment]
I have not seen this happen on my own stuff, do you know under what scenario this happens?

**Comment by rolfwessels** [comment]
I can't reproduce it on my side, but I change the bot to try to reconnect if the connection failed for any reason. Give it a try and let me know if the problem persists.
